name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.alsan-nvpc.org", custom_domain = true },
  { pattern = "quay.alsan-nvpc.org", custom_domain = true },
  { pattern = "gcr.alsan-nvpc.org", custom_domain = true },
  { pattern = "k8s-gcr.alsan-nvpc.org", custom_domain = true },
  { pattern = "k8s.alsan-nvpc.org", custom_domain = true },
  { pattern = "ghcr.alsan-nvpc.org", custom_domain = true },
  { pattern = "cloudsmith.alsan-nvpc.org", custom_domain = true },
  { pattern = "ecr.alsan-nvpc.org", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.alsan-nvpc.org", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""

[placement]
mode = "smart"
